[mongo]
host = "localhost"  # The host part of the MongoDB URI
port = 27017  # The port number, extracted from the URI
username = "E20030"  # Replace with your MongoDB username
password = "E20030"  # Replace with your MongoDB password
